version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: slsl-database-dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: slsldb
      MYSQL_USER: slsluser
      MYSQL_PASSWORD: slslpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./server/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./server/db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - slsl-network-dev

  # Backend Server (Development mode with hot reload)
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: slsl-server-dev
    environment:
      DB_URL: mysql://slsluser:slslpassword@db:3306/slsldb
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: slsluser
      DB_PASSWORD: slslpassword
      DB_NAME: slsldb
      NODE_ENV: development
    ports:
      - "8000:8000"
    volumes:
      - ./server/src:/app/src
    depends_on:
      - db
    networks:
      - slsl-network-dev
    command: npm run dev

  # Repetition Engine (Development mode)
  repetition-engine:
    build: 
      context: ./RepetitionEngineV1Synthetic
      dockerfile: Dockerfile
    container_name: slsl-repetition-engine-dev
    ports:
      - "5000:5000"
    volumes:
      - ./RepetitionEngineV1Synthetic:/app
    networks:
      - slsl-network-dev
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    command: python app.py

volumes:
  mysql_data_dev:
    driver: local

networks:
  slsl-network-dev:
    driver: bridge